name: Build and Deploy to ECR
description: Builds an image from a dockerfile, and pushes it up to ECR
inputs:
  access_key_id:
    description: AWS Access Key ID
    required: true
  architecture:
    description: Image architecture
    default: ""
    required: false
  build-args:
    description: List of build args to pass to Docker
    default: ""
    required: false
  build_config:
    description: File used during build (usually in postinstall) to install your app
    required: false
    default: ""
  deploy:
    description: Whether to push the image to ECR after building it
    required: false
    default: "true"
  dockerfile:
    description: Custom Dockerfile name
    required: false
    default: Dockerfile
  ecr_uri:
    description: The URI for the ECR repository
    required: true
  env_file:
    default: ""
    description: File containing environment variables required for app to run and pass healthcheck
    required: false
  github_ssh_key:
    description: SSH Private Key with access to any private repos you need
    required: false
    default: ""
  healthcheck:
    description: healthcheck path, like /healthcheck
    required: false
    default: /healthcheck
  platform:
    default: ""
    description: Image platform
    required: false
  port:
    description: Port the server listens on
    required: false
    default: "3000"
  registries:
    description: Credentials and host for pushing to multiple registries at once
    required: false
    default: ""
  secret_access_key:
    description: AWS Secret Access Key
    required: true

outputs:
  container-path:
    description: ECR path where image was pushed
    value: ${{ steps.setup.outputs.container-path }}
  github-sha:
    description: current github commit sha that triggered the workflow
    value: ${{ steps.setup.outputs.github-sha }}

runs:
  using: composite
  steps:
    - name: Versions
      shell: bash
      id: environment
      run: |
        echo '::group::docker version'
        docker version
        echo '::endgroup::'

        echo '::group::docker buildx version'
        if docker buildx version &> /dev/null; then
          docker buildx version
          echo '::set-output name=buildx::enabled'
        else
          echo 'buildx unavailable - $?'
        fi
        echo '::endgroup::'

        echo '::group::docker info'
        docker info
        echo '::endgroup::'

    # yamllint disable rule:line-length
    - name: Validate inputs
      shell: bash
      run: |
        # Did we even input, bro?
        test -z "${{inputs.ecr_uri}}" && echo '::error::The ecr_uri input is blank. This probably means that your secret is blank or does not exist. Make sure you have registered ecr repository with glgroup register-github-repo' && exit 2
        test -z "${{inputs.access_key_id}}" && echo '::error::The access_key_id input is blank. This probably means that your secret is blank or does not exist.' && exit 2
        test -z "${{inputs.secret_access_key}}" && echo '::error::The secret_access_key input is blank. This probably means that your secret is blank or does not exist.' && exit 2

        # ensure the dockerfile exists and is readable
        if [ -n '${{ inputs.dockerfile }}' ] && [ ! -r '${{ inputs.dockerfile }}' ]; then
          echo '::error::`${{ inputs.dockerfile }} was not found. If your Dockerfile has a custom name, please specify it using the `dockerfile: Dockerfile.prod` param.'
          exit 2
        fi

        # check for buildx flags when buildx is not enabled
        if [ '${{ steps.environment.outputs.buildx }}' != 'enabled' ]; then
          if [ -n '${{ inputs.platform }}' ]; then
            echo '::error::platform requested while buildx is not enabled. Please check your configuration and try again.'
            exit 3
          fi
        fi

    - name: Setup environment variables
      id: setup
      shell: bash
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        branch=$(cut --fields 3 --delimiter '/' <<< '${{ github.ref }}')
        ecr_repository="github/${{ github.repository }}/$branch"
        container_base=$(tr '[:upper:]' '[:lower:]' <<< "${{ inputs.ecr_uri }}/$ecr_repository")

        if [ -n '${{ inputs.architecture }}' ]; then
          prefix='${{ inputs.architecture }}-'
        else
          prefix=
        fi

        echo CONTAINER_IMAGE_LATEST=$container_base:${prefix}latest >> $GITHUB_ENV
        echo CONTAINER_IMAGE_SHA=$container_base:${prefix}${{ github.sha }} >> $GITHUB_ENV
        echo ECR_REPOSITORY=$ecr_repository >> $GITHUB_ENV

        # Only include the GITHUB_SSH_KEY if it exists
        if [ -n '${{ inputs.github_ssh_key }}' ]; then
          # if dockerfile requests buildkit functionality, appease it
          # otherwise default to the build argument
          if grep --quiet 'mount=type=ssh' './${{ inputs.dockerfile }}'; then
            ssh-agent -a $SSH_AUTH_SOCK
            base64 --decode <<< "${{ inputs.github_ssh_key }}" | ssh-add -

            echo '::set-output name=docker-buildkit::1'
            echo ARG_GITHUB_SSH_KEY="--ssh default=$SSH_AUTH_SOCK" >> $GITHUB_ENV
          else
            echo ARG_GITHUB_SSH_KEY='--build-arg GITHUB_SSH_KEY=${{ inputs.github_ssh_key }}' >> $GITHUB_ENV
          fi
        fi

        # Only include the GITHUB_SHA if it is used (suppresses a warning)
        if grep --quiet GITHUB_SHA './${{ inputs.dockerfile }}'; then
          echo ARG_GITHUB_SHA='--build-arg GITHUB_SHA=${{ github.sha }}' >> $GITHUB_ENV
        fi

        if [ -n '${{ inputs.dockerfile }}' ] && [ '${{ inputs.dockerfile }}' != 'Dockerfile' ]; then
          echo CUSTOM_DOCKERFILE='-f ${{ inputs.dockerfile }}' >> $GITHUB_ENV
        fi

        if [ -n '${{ inputs.build_config }}' ]; then
          echo ARG_BUILD_CONFIG='--build-arg BUILD_CONFIG=${{ inputs.build_config }}' >> $GITHUB_ENV
        fi

        if [ -n '${{ inputs.env_file }}' ]; then
          echo ENV_FILE='--env-file ${{ inputs.env_file }}' >> $GITHUB_ENV
        fi

        if [ '${{ steps.environment.outputs.buildx }}' = 'enabled' ]; then
          if [ -n '${{ inputs.platform }}' ]; then
            echo PLATFORM='--platform ${{ inputs.platform }} --load' >> $GITHUB_ENV
          fi
        fi

        # Look for future "RUN <<" syntax and enable buildkit
        if grep --ignore-case --quiet '^\s*run\s\?<<' './${{ inputs.dockerfile }}'; then
          echo '::set-output name=docker-buildkit::1'
        fi

        echo "::set-output name=aws-region::$(cut --fields 4 --delimiter '.' <<< '${{ inputs.ecr_uri }}')"
        echo "::set-output name=base-container-image::$container_base"
        echo "::set-output name=container-path::$(cut --fields 2- --delimiter '/' <<< "$container_base")"
        echo '::set-output name=github-sha::${{ github.sha }}'

    - name: Ensure ECR Repository Exists
      shell: bash
      id: assert-ecr-repo
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.secret_access_key }}
        AWS_REGION: us-east-1
      run: |
        echo "Checking for ECR Repository: $ECR_REPOSITORY"
        set +e
        log1=/tmp/describe-error.log
        ecr_repo=$(aws ecr describe-repositories --repository-names "$ECR_REPOSITORY" --debug 2>$log1)

        if [ -f $log1 ]; then
          cat $log1
        fi

        if [ -z "$ecr_repo"]; then
          log2=/tmp/create-error.log
          echo "Creating ECR Repository: $ECR_REPOSITORY"
          created=$(aws ecr create-repository --repository-name "$ECR_REPOSITORY" --tags "Key=ManagedBy,Value=GitHub" --debug 2>$log2)

          if [ -f $log2 ]; then
            cat $log2
          fi

          if [ -z "$created" ]; then
            echo "Could not create ECR Repository: $ECR_REPOSITORY"
            echo "Please re-register this repository to get updated credentials:"
            echo "    glgroup ecr register-github-repo -r ${{ github.event.repository.name }} -b main"
            exit 1
          fi
        fi
        set -e

    - name: Get ECR login password
      shell: bash
      id: get-login-password
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.secret_access_key }}
      run: |
        login_password="$(aws ecr get-login-password --region '${{ steps.setup.outputs.aws-region }}')"
        echo "::add-mask::$login_password"

        if [ -z "$login_password" ]; then
          echo '::error::Unable to obtain ECR password'
          exit 4
        fi

        echo "::set-output name=password::$login_password"
    - name: Docker login
      shell: bash
      run: >
        docker login
        --username AWS
        --password '${{ steps.get-login-password.outputs.password }}'
        ${{ inputs.ecr_uri }}

    - name: Parse registries
      id: registries
      shell: bash
      run: |
        hosts="${{ inputs.ecr_uri }} "

        if [ -n '${{ inputs.registries }}' ]; then
          # if it contains a comma, split on commas
          if [[ '${{ inputs.registries }}' == *","* ]]; then
            echo '::debug::parse found a comma'
            IFS=','
            read -ra urls <<< '${{ inputs.registries }}'
          else
            echo '::debug::parse using readarray'
            readarray -t urls <<< "${{ inputs.registries }}"
          fi

          aws_url='aws://([^:]+):([^@]+)@([0-9a-zA-Z.-]+)'
          tags=""

          echo "::debug::Found ${#urls[@]} registries entries"

          for url in "${urls[@]}"; do
            if [[ $url =~ $aws_url ]]; then
              region="$(cut --fields 4 --delimiter '.' <<< "${BASH_REMATCH[3]}")"

              AWS_ACCESS_KEY_ID=${BASH_REMATCH[1]} \
              AWS_SECRET_ACCESS_KEY=${BASH_REMATCH[2]} \
              aws ecr get-login-password \
                --region $region | docker login \
                --username AWS \
                --password-stdin ${BASH_REMATCH[3]}

              hosts+="${BASH_REMATCH[3]} "
              tags+="--tag ${BASH_REMATCH[3]}/${{ steps.setup.outputs.container-path }}:latest "
              tags+="--tag ${BASH_REMATCH[3]}/${{ steps.setup.outputs.container-path }}:${{ github.sha }} "
            elif [ -z "$url" ]; then
              # ignore blank lines
              continue
            else
              echo "::warning::Bad registries value - $url"
            fi
          done

          if [ -n "$tags" ]; then
            echo '::debug::adding registries tags'
            echo ARG_MULTIPASS_TAGS="$tags" >> $GITHUB_ENV
          fi
        fi

        echo "::set-output name=registry-hosts::$hosts"

    - name: Parse build-args
      shell: bash
      run: |
        if [ -n '${{ inputs.build-args }}' ]; then
          build_args=""

          readarray -t args <<< "${{ inputs.build-args }}"
          for a in "${args[@]}"; do
            # skip blank lines
            if [ -z "$a" ]; then
              continue
            fi

            build_args+="--build-arg $a "
          done

          echo CUSTOM_BUILD_ARGS="$build_args" >> $GITHUB_ENV
        fi

    - name: Docker build
      shell: bash
      env:
        # equivalent to --progress=plain
        BUILDKIT_PROGRESS: plain
        # https://docs.docker.com/develop/develop-images/build_enhancements/#to-enable-buildkit-builds
        DOCKER_BUILDKIT: ${{ steps.setup.outputs.docker-buildkit }}
      run: >
        docker build
        --tag $CONTAINER_IMAGE_SHA
        --tag $CONTAINER_IMAGE_LATEST
        $ARG_MULTIPASS_TAGS
        $CUSTOM_DOCKERFILE
        $CUSTOM_BUILD_ARGS
        $ARG_BUILD_CONFIG
        $ARG_GITHUB_SSH_KEY
        $ARG_GITHUB_SHA
        $PLATFORM
        .

    - name: Check health
      shell: bash
      run: |
        if [ -n '${{ inputs.healthcheck }}' ]; then
          # Healthcheck the built container
          docker run --detach \
            --net host \
            --publish ${{inputs.port}}:${{inputs.port}} \
            $ENV_FILE \
            --env "HEALTHCHECK=${{inputs.healthcheck}}" \
            --env "PORT=${{inputs.port}}" \
            --name test-container $CONTAINER_IMAGE_SHA

          ATTEMPT_COUNT=0
          MAX_ATTEMPTS=5

          HEALTHCHECK="http://localhost:${{inputs.port}}${{inputs.healthcheck}}"

          until $(curl --output /dev/null --silent --head --fail --max-time 5 "${HEALTHCHECK}"); do
            if [ "$((++ATTEMPT_COUNT))" -gt "${MAX_ATTEMPTS}" ];then
              echo "::error::Container did not pass healthcheck at $HEALTHCHECK after $MAX_ATTEMPTS attempts"
              echo "::warning::If your container does not require a healthcheck (most jobs don't), then set healthcheck to a blank string."
              echo "::group::docker logs"
              docker logs test-container
              echo "::endgroup::"
              echo $(docker stop test-container) stopped.
              exit 1
            fi

            sleep 5
            echo "Tested healthcheck ${HEALTHCHECK} : Attempt ${ATTEMPT_COUNT} of ${MAX_ATTEMPTS}"
          done

          echo "Healthcheck passed!"
          echo $(docker stop test-container) stopped.
        else
          echo '::warning::No healthcheck specified'
        fi
    - name: Push to ECR
      shell: bash
      run: |
        if [ '${{ inputs.deploy }}' = 'true' ]; then
          docker push ${{ steps.setup.outputs.base-container-image }} --all-tags
        fi

    - name: Log out of all registries
      shell: bash
      run: |
        for host in ${{ steps.registries.outputs.registry-hosts }} ; do
          docker logout $host
        done
