name: Build and Deploy to ECR
description: Builds an image from a dockerfile, and pushes it up to ECR
inputs:
  access_key_id:
    description: AWS Access Key ID
    required: true
  architecture:
    description: Image architecture
    default: ""
    required: false
  build-args:
    description: List of build args to pass to Docker
    default: ""
    required: false
  build_config:
    description: File used during build (usually in postinstall) to install your app
    required: false
    default: ""
  buildkit:
    description: Use Docker Buildkit
    required: false
    default: "true"
  deploy:
    description: Whether to push the image to ECR after building it
    required: false
    default: "true"
  dockerfile:
    description: Custom Dockerfile name
    required: false
    default: Dockerfile
  ecr_uri:
    description: The URI for the ECR repository
    required: true
  env_file:
    default: ""
    description: File containing environment variables required for app to run and pass healthcheck
    required: false
  github_ssh_key:
    description: SSH Private Key with access to any private repos you need
    required: false
    default: ""
  github_packages_token:
    description: Github token with permissions to read from the github packages registry
    required: false
    default: ""
  healthcheck:
    description: healthcheck path, like /healthcheck
    required: false
    default: /healthcheck
  platform:
    default: ""
    description: Image platform
    required: false
  port:
    description: Port the server listens on
    required: false
    default: "3000"
  registries:
    description: Credentials and host for pushing to multiple registries at once
    required: false
    default: ""
  secret_access_key:
    description: AWS Secret Access Key
    required: true
  secrets_file:
    description: Path to an env file to be mounted as a secret during the build phase of your container
    required: false
  working_directory:
    description: The path to use as the build context, in case you need something besides project root.
    required: false
    default: "."

outputs:
  container-path:
    description: ECR path where image was pushed
  github-sha:
    description: current github commit sha that triggered the workflow

runs:
  using: node16
  main: index.js
